# Copyright (c) 2018, NVIDIA CORPORATION.

dist: trusty
sudo: required
language: python

branches:
    only:
        - master
env:
  global:
  - secure: XHN+jQNVZUgXP5Qp66kzeu3MTuAjTdom+4GK7UEW2DnT1vR+acUmIBYNcuhDghZEuegXQc1jWwslQKq102SU19E0KzzSJgBN1UQyv3j2i3tBp3+qaTNDCVU26hGydtyoQox0XL5XaV2ZO19PTwH94Vc5fRV+KtDk/onoxhNs62A+TQf7DZuV8IoWHuIMYTw9QlBpXlGdays/xBCXZYwD06EFe6G54u689CXMrx/6ZdUhDsLLx3Up1pFM58cxozKyCVfY1S679VWlXQ+3SCPELT44dNpHTHsK19UY6jsWdDmwwSYtrML+/aq1U5LvGmUphi8Zxvn8AJdicop8xF7UjUt4QsbbdxEWa5F3YCaPkXjANnQMQ265gfIswQ/rrb26U6qqESg5lq10gl96bubTQ9IcpN9F6JvcFPJ8LcYAZ/kad0slXGduscRmiCcnmREOTN7g+CMZcdUzLODuA/QhP99EByW48QX/q8b/C7UAiWlBd+4l+IIquGT8Y2NbuWHJD1ty/Mt61eyRLkK2rHw+j+xGCqgPjHp+ObI+kN0VRkp/7M1GGw5CHZ4NmkyjkroxoGN2N5GqAs1gHIoD4MlkUaF+K/Si7sPJpwNj56POD4iyAcBSzCCVxHKx/1MbPmh1cqy5fCkmte7agWfO5dLSELCc7fHvmYuL8dei/YJtme0=


matrix:
  include:
    - env: CUDA=9.2.148_396.37 PYTHON=3.5 LABEL_MAIN=1 BUILD_CUDF=1 BUILD_LIBGDF=1 BUILD_CFFI=1
    - env: CUDA=9.2.148_396.37 PYTHON=3.6 LABEL_MAIN=1 BUILD_CUDF=1 BUILD_CFFI=1
    - env: CUDA=10.0.130_410.48 PYTHON=3.5 BUILD_LIBGDF=1 BUILD_CFFI=1
    - env: CUDA=10.0.130_410.48 PYTHON=3.6 BUILD_CFFI=1

before_install:
  # install build environment for libgdf
  - source ./travisci/libgdf/install-env-libgdf.sh
  # install miniconda
  - travis_retry wget --progress=dot:mega https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH

install:
  # check
  - conda --version
  # install conda build
  - conda install conda-build anaconda-client flake8 conda-verify cmake=3.12 --yes
script:
  # Activate root environment for cmake
  - source activate root
  # check conda versions
  - conda list
  # build ligdf
  - source ./travisci/libgdf/build_libgdf.sh
  # build libgdf_cffi
  - source ./travisci/libgdf/build_libgdf_cffi.sh
  # upload libgdf and libgdf_cffi
  - source ./travisci/libgdf/upload.sh
  # build cudf
  - source ./travisci/build_cudf.sh
  - flake8

after_success:
  # upload cudf
  - source ./travisci/upload-anaconda.sh
