name: "Auto Assign PR"

on:
  pull_request:
    types:
      - opened

jobs:
  add_assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          assignees: ${{ github.actor }}
